# Generated by Django 5.2.8 on 2026-02-19 18:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(help_text='Name of the airline', max_length=255)),
                ('airline_code', models.CharField(blank=True, default='', help_text='IATA airline code (e.g. LA, SK, LH)', max_length=10)),
                ('sender_pattern', models.TextField(help_text='Regex pattern to match the email sender (From header)')),
                ('subject_pattern', models.TextField(blank=True, default='', help_text='Optional regex for matching email subject')),
                ('body_pattern', models.TextField(help_text='Regex pattern with named groups applied to email body (plain text or HTML stripped)')),
                ('date_format', models.CharField(default='%d %b %Y', help_text="Python strptime format for dates, e.g. '%%d %%b %%Y'", max_length=64)),
                ('time_format', models.CharField(default='%H:%M', help_text="Python strptime format for times, e.g. '%%H:%%M'", max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in rules ship with the system')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are tried first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for system-wide built-in rules', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'airline_name'],
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this email account', max_length=255)),
                ('email_address', models.EmailField(help_text='Email address used to connect', max_length=254)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail (IMAP/OAuth)'), ('outlook', 'Outlook (IMAP)'), ('imap', 'Generic IMAP'), ('tuta', 'Tuta (Tutanota)')], default='imap', max_length=20)),
                ('imap_host', models.CharField(blank=True, default='', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_username', models.CharField(blank=True, default='', max_length=255)),
                ('imap_password', models.CharField(blank=True, default='', help_text='App password or OAuth token for IMAP login', max_length=1024)),
                ('use_ssl', models.BooleanField(default=True)),
                ('tuta_user', models.CharField(blank=True, default='', max_length=255)),
                ('tuta_password', models.CharField(blank=True, default='', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'email_address')},
            },
        ),
        migrations.CreateModel(
            name='FlightGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Trip name, e.g. 'Brazil Trip 2026'", max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='True if this group was auto-created from booking references')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline_name', models.CharField(blank=True, default='', max_length=255)),
                ('airline_code', models.CharField(blank=True, default='', max_length=10)),
                ('flight_number', models.CharField(max_length=20)),
                ('booking_reference', models.CharField(blank=True, default='', max_length=50)),
                ('departure_airport', models.CharField(help_text='IATA airport code', max_length=10)),
                ('departure_city', models.CharField(blank=True, default='', max_length=255)),
                ('departure_datetime', models.DateTimeField()),
                ('departure_terminal', models.CharField(blank=True, default='', max_length=20)),
                ('departure_gate', models.CharField(blank=True, default='', max_length=20)),
                ('arrival_airport', models.CharField(help_text='IATA airport code', max_length=10)),
                ('arrival_city', models.CharField(blank=True, default='', max_length=255)),
                ('arrival_datetime', models.DateTimeField()),
                ('arrival_terminal', models.CharField(blank=True, default='', max_length=20)),
                ('arrival_gate', models.CharField(blank=True, default='', max_length=20)),
                ('passenger_name', models.CharField(blank=True, default='', max_length=255)),
                ('seat', models.CharField(blank=True, default='', max_length=10)),
                ('cabin_class', models.CharField(blank=True, choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First')], default='', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('email_subject', models.CharField(blank=True, default='', max_length=512)),
                ('email_date', models.DateTimeField(blank=True, null=True)),
                ('email_message_id', models.CharField(blank=True, default='', help_text='Message-ID header or UID for deduplication', max_length=512)),
                ('is_manually_added', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.airlinerule')),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flights.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
                ('flight_group', models.ForeignKey(blank=True, help_text='Trip/group this flight belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flights.flightgroup')),
            ],
            options={
                'ordering': ['-departure_datetime'],
                'unique_together': {('user', 'email_message_id')},
            },
        ),
    ]
