# Generated by Django 5.2.11 on 2026-02-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0071_alter_collectionitineraryitem_unique_together_and_more'),
        ('flights', '0004_remove_emailaccount_tuta_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_datetime']},
        ),
        migrations.AddField(
            model_name='flight',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection/trip this flight is linked to', null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.collection'),
        ),
    ]
