# Generated by Django 5.2.11 on 2026-02-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0071_alter_collectionitineraryitem_unique_together_and_more'),
        ('flights', '0005_alter_flight_options_flight_collection'),
        ('worldtravel', '0018_rename_user_id_visitedcity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightgroup',
            name='collection',
            field=models.OneToOneField(blank=True, help_text='Auto-created collection for this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_group', to='adventures.collection'),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(help_text='IATA 3-letter code', max_length=3, primary_key=True, serialize=False)),
                ('icao_code', models.CharField(blank=True, default='', max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('city_name', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('region_code', models.CharField(blank=True, default='', help_text='ISO 3166-2 code, e.g. US-CA, BR-SP', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('worldtravel_city', models.ForeignKey(blank=True, help_text='Nearest matching city in the WorldTravel database', null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldtravel.city')),
            ],
            options={
                'verbose_name': 'Airport',
                'ordering': ['iata_code'],
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport_obj',
            field=models.ForeignKey(blank=True, help_text='Resolved airport object for arrival', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport_obj',
            field=models.ForeignKey(blank=True, help_text='Resolved airport object for departure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departures', to='flights.airport'),
        ),
    ]
